FROM continuumio/miniconda3

# Install dependencies
ENV PATH="/opt/conda/bin/:${PATH}"
RUN apt-get update && apt-get install -y gcc && \
    conda install cudatoolkit==9.2 tensorflow-gpu==1.13.1

# Install PiNN
COPY . /opt/src/pinn
RUN pip install /opt/src/pinn && \
    pip install -r /opt/src/pinn/requirements-dev.txt && \
    pip install -r /opt/src/pinn/requirements-extra.txt && \
    jupyter nbextension enable widgetsnbextension --py --sys-prefix && \
    jupyter nbextension enable nglview --py --sys-prefix && \
    jupyter tensorboard enable --sys-prefix 

# Setup
ENTRYPOINT ["pinn_train"]
