#+TITLE: Pairwise interaction neural network
#+BEGIN_HTML
<img src="https://travis-ci.org/yqshao/pinn.svg?branch=master">
#+END_HTML
PiNN is a atomic neural network potential algorithm. This package is currently being developed primarily by Yunqi Shao at East China University of Science and Technology (ECUST), and is published under the GNU General Public Licence. The pinn package is designed to work with ASE and tensorflow.

* License
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

* Installation
#+BEGIN_SRC bash
  git clone https://github.com/yqshao/pinn.git
  cd pinn
  pip install -e .
#+END_SRC
